name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment variables for secrets
      run: |
        echo "API_KEY=${{ secrets.APIKEY }}" >> $GITHUB_ENV
        echo "CLIENT_ID=${{ secrets.CLIENTID }}" >> $GITHUB_ENV
      id: set_secrets

    - name: Inject secrets into the code
      run: |
        # Use 'envsubst' to replace placeholders with actual secrets
        envsubst < app.js > app_temp.js && mv app_temp.js app.js

    - name: Debug app.js content
      run: cat app.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
