name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject secrets into config.js
      run: |
        echo "const CONFIG = {" > ./config.js
        echo "  API_KEY: '${{ secrets.APIKEY }}'," >> ./config.js
        echo "  CLIENT_ID: '${{ secrets.CLIENTID }}'" >> ./config.js
        echo "};" >> ./config.js
        echo "export default CONFIG;" >> ./config.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
