name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inject secrets into config.js
      run: |
        echo "const CONFIG = {" > ./config.js
        echo "  API_KEY: '${{ secrets.APIKEY }}'," >> ./config.js
        echo "  CLIENT_ID: '${{ secrets.CLIENTID }}'" >> ./config.js
        echo "};" >> ./config.js
        echo "export default CONFIG;" >> ./config.js

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add -f config.js # Force-add ignored file
        git commit -m "Automated config.js update" || echo "No changes to commit"
        git push
